from django.db import models

# Create your models here.
from django.db import models

class funding(models.Model):
    # name = models.CharField(max_length=100)  # Replace with your actual form fields
    # email = models.EmailField()
    # message = models.TextField()
    # submitted_at = models.DateTimeField(auto_now_add=True)
    id = models.AutoField(primary_key=True) # Integer as primary key
    first_name = models.TextField()  # First name as an integer
    last_name = models.TextField()  # Last name as an integer
    title = models.TextField(null=True, blank=True)
    company = models.TextField(max_length=255)
    company_name_for_emails = models.TextField(null=True, blank=True)
    email = models.TextField(null=True, blank=True)
    phone = models.TextField(max_length=15, null=True, blank=True)
    employees = models.IntegerField(null=True, blank=True)
    industry = models.TextField(null=True, blank=True)
    keywords = models.TextField(null=True, blank=True)
    person_linkedin_url = models.TextField(null=True, blank=True)
    website = models.TextField(null=True, blank=True)
    company_linkedin_url = models.TextField(null=True, blank=True)
    facebook_url = models.TextField(null=True, blank=True)
    twitter_url = models.TextField(null=True, blank=True)
    city = models.TextField(null=True, blank=True)
    state = models.TextField(null=True, blank=True)
    country = models.TextField(null=True, blank=True)
    company_address = models.TextField(null=True, blank=True)
    company_city = models.TextField(null=True, blank=True)
    company_state = models.TextField(null=True, blank=True)
    company_country = models.TextField(null=True, blank=True)
    company_phone = models.TextField(max_length=15, null=True, blank=True)
    seo_description = models.TextField(null=True, blank=True)
    annual_revenue = models.TextField(null=True, blank=True)
    total_funding = models.TextField(null=True, blank=True)
    latest_funding = models.TextField(null=True, blank=True)
    latest_funding_amount = models.TextField(null=True, blank=True)
    last_raised_at = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.name} - {self.email}"
    
class india_vc(models.Model):
    name = models.TextField(null=True, blank=True) 
    firm_name = models.TextField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    founder_year = models.TextField(null=True, blank=True)
    ticket_size = models.TextField(null=True, blank=True)
    current_fund_size = models.TextField(null=True, blank=True)
    aum = models.TextField(null=True, blank=True)
    portfolio_count = models.TextField(null=True, blank=True)
    portfolio_companies = models.TextField(null=True, blank=True)
    prefer_lead_rounds = models.TextField(null=True, blank=True)
    stage_focus_pre_seed = models.TextField(null=True, blank=True)
    stage_focus_seed = models.TextField(null=True, blank=True)
    stage_focus_series_a = models.TextField(null=True, blank=True)
    stage_focus_series_b = models.TextField(null=True, blank=True)
    stage_focus_series_c = models.TextField(null=True, blank=True)
    stage_focus_debt = models.TextField(null=True, blank=True)
    sector_focus_ai_ml = models.TextField(null=True, blank=True)
    sector_focus_ar_vr = models.TextField(null=True, blank=True)
    sector_focus_agritech_food = models.TextField(null=True, blank=True)
    sector_focus_biotech_life_sciences = models.TextField(null=True, blank=True)
    sector_focus_climate_sustainability = models.TextField(null=True, blank=True)
    sector_focus_consumer = models.TextField(null=True, blank=True)
    sector_focus_crypto_blockchain = models.TextField(null=True, blank=True)
    sector_focus_deep_tech = models.TextField(null=True, blank=True)
    sector_focus_education = models.TextField(null=True, blank=True)
    sector_focus_enterprise = models.TextField(null=True, blank=True)
    sector_focus_media_entertainment = models.TextField(null=True, blank=True)
    sector_focus_fintech = models.TextField(null=True, blank=True)
    sector_focus_gaming = models.TextField(null=True, blank=True)
    sector_focus_government_defence = models.TextField(null=True, blank=True)
    sector_focus_health_wellness = models.TextField(null=True, blank=True)
    sector_focus_healthcare_medtech = models.TextField(null=True, blank=True)
    sector_focus_industrial_iot_robotics = models.TextField(null=True, blank=True)
    sector_focus_prop_tech_real_estate = models.TextField(null=True, blank=True)
    sector_focus_saas_devops_marketplace = models.TextField(null=True, blank=True)
    sector_focus_supply_chain_logistics = models.TextField(null=True, blank=True)
    sector_focus_travel_hospitality = models.TextField(null=True, blank=True)
    founder_preference_warm_intro = models.TextField(null=True, blank=True)
    founder_preference_twitter_dm = models.TextField(null=True, blank=True)
    founder_preference_linkedin = models.TextField(null=True, blank=True)
    founder_preference_investment_bankers = models.TextField(null=True, blank=True)
    founder_preference_fund_application_form = models.TextField(null=True, blank=True)
    founder_preference_cold_mail = models.TextField(null=True, blank=True)
    founder_preference_other = models.TextField(null=True, blank=True)
    founder_preference_other_name = models.TextField(null=True, blank=True)
    fund_application_form = models.TextField(null=True, blank=True)
    poc_mail = models.TextField(null=True, blank=True)
    fund_overview = models.TextField(null=True, blank=True)

    investment_process = models.TextField(null=True, blank=True)
    turn_around_time = models.TextField(null=True, blank=True)
    fund_preferences = models.TextField(null=True, blank=True)
    other_remarks = models.TextField(null=True, blank=True)
    interested_newsletter = models.TextField(null=True, blank=True)

class spotlight(models.Model):
    name = models.TextField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    company_name = models.TextField(null=True, blank=True)

class launchpad(models.Model):
    name = models.TextField(null=True, blank=True)
    firm_name = models.TextField(null=True, blank=True)
    mail = models.TextField(null=True, blank=True)
    role_name = models.TextField(null=True, blank=True)
    role_type = models.TextField(null=True, blank=True)
    role_location = models.TextField(null=True, blank=True)
    about_job = models.TextField(null=True, blank=True)
    job_application_link = models.TextField(null=True, blank=True)
    interested_newsletter_story = models.TextField(null=True, blank=True)

class tech_stack_waitlist(models.Model):
    name = models.TextField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    firm_name = models.TextField(null=True, blank=True)
    interested_newsletter_story = models.TextField(null=True, blank=True)
