# Generated by Django 5.1.4 on 2024-12-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormDataHistory',
            new_name='TanFunding',
        ),
    ]
