# Generated by Django 5.1.4 on 2024-12-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tan', '0002_rename_formdatahistory_tanfunding'),
    ]

    operations = [
        migrations.CreateModel(
            name='funding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('title', models.TextField(blank=True, null=True)),
                ('company', models.TextField(max_length=255)),
                ('company_name_for_emails', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, max_length=15, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('person_linkedin_url', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('company_linkedin_url', models.TextField(blank=True, null=True)),
                ('facebook_url', models.TextField(blank=True, null=True)),
                ('twitter_url', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_city', models.TextField(blank=True, null=True)),
                ('company_state', models.TextField(blank=True, null=True)),
                ('company_country', models.TextField(blank=True, null=True)),
                ('company_phone', models.TextField(blank=True, max_length=15, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('annual_revenue', models.TextField(blank=True, null=True)),
                ('total_funding', models.TextField(blank=True, null=True)),
                ('latest_funding', models.TextField(blank=True, null=True)),
                ('latest_funding_amount', models.TextField(blank=True, null=True)),
                ('last_raised_at', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TanFunding',
        ),
    ]
