# Generated by Django 5.1.4 on 2025-01-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tan', '0004_india_vc_launchpad_spotlight_tech_stack_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='vc_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('start_up_name', models.TextField(blank=True, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('founders_linkedin_profiles', models.TextField(blank=True, null=True)),
                ('product_website', models.TextField(blank=True, null=True)),
                ('funding_amount', models.TextField(blank=True, null=True)),
                ('pitch_deck', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
