# Generated by Django 5.1.4 on 2025-01-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tan', '0005_vc_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='india_vc',
        ),
        migrations.RenameField(
            model_name='funding',
            old_name='annual_revenue',
            new_name='companyLinkedinUrl',
        ),
        migrations.RenameField(
            model_name='funding',
            old_name='city',
            new_name='companyOverview',
        ),
        migrations.RenameField(
            model_name='funding',
            old_name='company_address',
            new_name='currentFundCorpus',
        ),
        migrations.RenameField(
            model_name='funding',
            old_name='company_linkedin_url',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='funding',
            old_name='company_name_for_emails',
            new_name='totalFundCorpus',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='company_state',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='country',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='email',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='last_raised_at',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='latest_funding',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='latest_funding_amount',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='person_linkedin_url',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='state',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='total_funding',
        ),
    ]
