# Generated by Django 5.1.4 on 2025-01-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tan', '0006_delete_india_vc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding',
            old_name='company_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='funding',
            old_name='company_country',
            new_name='country',
        ),
    ]
