# Generated by Django 5.1.4 on 2025-01-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tan', '0008_registration_delete_funding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='company_linkedin_url',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='company_overview',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='current_fund_corpus',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='ticket_size',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='total_fund_corpus',
        ),
        migrations.AddField(
            model_name='registration',
            name='companyLinkedinUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='companyOverview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='currentFundCorpus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='totalFundCorpus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='company',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='twitter_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
