# Generated by Django 5.1.4 on 2025-01-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tan', '0009_remove_registration_company_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='twitter_url',
            new_name='twitterUrl',
        ),
    ]
