# Generated by Django 5.1.4 on 2025-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tan', '0010_rename_twitter_url_registration_twitterurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='sectors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='stages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='ticketSize',
            field=models.TextField(blank=True, null=True),
        ),
    ]
