# Generated by Django 5.1.4 on 2025-01-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tan', '0011_registration_sectors_registration_stages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='sectors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='stages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
